### ISSUE TITLE
Multiple issues

### ISSUE THREAD

**Issue by crtnx** [fastdatascience/countryfinder#1]
Hi,

thanks for the wonderful work done. Here is the list of issues I've just found:

1. Typing hint for find_countries method is wrong, it should be a list instead of str
2. When I've tried to run find_countries("P.O.Box 116199, Dubai, U.A.E") it didn't find anything.
3. Potentially you could export add_variants method to add more custom variants, like "U.A.E" in my case

**Comment by woodthom2** [comment]
Thanks very much! I'll take a look when I get a moment but feel free to make a pull request if you can see an easy fix

**Comment by woodthom2** [comment]
I've updated the version to 0.4 and fixed these problems. You can now add custom variants

```
from country_named_entity_recognition import find_countries, add_custom_variants
add_custom_variants(["Neverneverland"], "AE")
find_countries("I want to visit Neverneverland")
```
